on: [push, pull_request]
name: Linter

jobs:
  build:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "*"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black ruff

      - name: Check styling with black
        run: |
          black --check *.py

      - name: Run ruff linter
        run: |
          ruff check *.py
